### ISSUE TITLE
Parallel work going on in codemirror/lang-liquid

### ISSUE THREAD

**Issue by marijnh** [harttle/codemirror-lang-liquid#1]
We seem to have started on this at pretty much the same moment. See https://github.com/codemirror/lang-liquid . Just a heads-up in case you want to stop and use whatever I end up releasing instead.

**Comment by harttle** [comment]
Thank you @marijnh for the heads up, good to see codemirror is officially supporting Liquid. While I didn’t find this when I started. It took me a while to understand lezer grammar but now this project can be completed in a few days.

I started this per requests under https://github.com/harttle/liquidjs , as the author I guess maybe I know better about syntax details. Anyway we can combine the efforts? Maybe send you a link when this finished and help review my implementation and see what is missing?

**Comment by harttle** [comment]
Merged comment/mixedParser from codemirror/lang-liquid, added autocomplete.

**Comment by marijnh** [comment]
I've published a finished version of my package as @codemirror/lang-liquid. Indentation of this type of language in general should be better with changes in @codemirror/language 6.9.1.

Do you want me to list codemirror-lang-liquid on the [community](https://codemirror.net/docs/community/) package page?

**Comment by harttle** [comment]
Sure, please do.

I find folding is not working properly when wrap with a mixedparser, otherwise it’s OK. Any ideas on this?

**Comment by marijnh** [comment]
> I find folding is not working properly when wrap with a mixedparser,

Did you try with @codemirror/language 6.9.1?

**Comment by harttle** [comment]
Wow! It works like a charm! Thank you @marijnh.

Closing this.
